### ISSUE TITLE
Missing a white space ;)

### ISSUE THREAD

**Issue by BlinkSun** [aflashyrhetoric/NightMessenger#12]
`<div class="_4sp8">`
Need to be set background-color: $darkgray when you start to search for something in the search box over the contacts list. :sob:
![image](https://user-images.githubusercontent.com/7069760/47543228-2b2c4c80-d8af-11e8-9d39-f73e34b3801a.png)

---------

Suggestion: I set some "custom" color to specifics contacts, but when turn Night mode, all turn same $accent color :disappointed:. I don't, maybe rethink about not to change it and adjust the forecolor ... :thinking: ... only a suggestion but keeping my "custom" color for my specifics contacts in Night mode would be really cool !![image](https://user-images.githubusercontent.com/7069760/47543118-b22cf500-d8ae-11e8-8121-fa3ab1e5c692.png)

**Comment by aflashyrhetoric** [comment]
Thank you very much! I'm very sorry for the delay - I've just been swamped with some other work. I've got a fix pending and should push it today.

**Comment by aflashyrhetoric** [comment]
I've updated the chrome extension - it should be hitting your browser any moment now. Please let me if you still notice the error and I'll try to fix it promptly - thank you very much!
