### ISSUE TITLE
highlight of selected chat is missing

### ISSUE THREAD

**Issue by henriklb** [aflashyrhetoric/NightMessenger#13]
Hi and thanks for this extension.

However, one small issue is that the grey highlight (in normal light mode) of the current selected chat is not visible with this extension. This makes it not possible to know which conversation is currently selected by looking at the list of conversations to the left.

**Comment by aflashyrhetoric** [comment]
Sorry for the delay - I honestly was just caught up with work, but I'll be working on these and all the other relevant issues soon - thank you so much for your feedback! 🙇

**Comment by henriklb** [comment]
Thank you for the extension!

**Comment by aflashyrhetoric** [comment]
I've updated the chrome extension - it should be hitting your browser any moment now. Please let me if you still notice the error and I'll try to fix it promptly - thank you very much!
