### ISSUE TITLE
White space when other person is typing

### ISSUE THREAD

**Issue by blakebuthod** [aflashyrhetoric/NightMessenger#14]
Classes: clearfix _17pz

![image](https://user-images.githubusercontent.com/17950836/52067106-82415d80-253f-11e9-9f2c-1dab3773e5a3.png)

**Comment by aflashyrhetoric** [comment]
Thank you for the bug report - working on this now!

**Comment by aflashyrhetoric** [comment]
I've updated the chrome extension - it should be hitting your browser any moment now. Please let me if you still notice the error and I'll try to fix it promptly - thank you very much!

**Comment by blakebuthod** [comment]
Fixed with `1.3.0`. Thank you!
