### ISSUE TITLE
White space at the bottom of GIFs

### ISSUE THREAD

**Issue by blakebuthod** [aflashyrhetoric/NightMessenger#20]
This one's pretty minor. Looks like the class is `._2f5n`.

![image](https://user-images.githubusercontent.com/17950836/56054753-44ba3700-5d1d-11e9-844b-1559461d4226.png)

Would recommend the color match the sender color,`#223176`, with white text like this:

![image](https://user-images.githubusercontent.com/17950836/56054871-96fb5800-5d1d-11e9-9faf-518f7a492024.png)

**Comment by blakebuthod** [comment]
Actually, you could make it one color for sent and another for received to match the other messages. Here's what got that working for me:

```
._3i_m._nd_ ._2f5n._4br2._29ew
{
    background-color: #223176 !important;
}
._29_7 ._2f5n._4br2._29ew
{
    background-color: #35393d !important;
}
._2f5n._4br2._29ew span
{
    color: #d4d4d6 !important;
}
```

**Comment by aflashyrhetoric** [comment]
Added and will be released soon - cheers!
