### ISSUE TITLE
White space around emoji reacts

### ISSUE THREAD

**Issue by blakebuthod** [aflashyrhetoric/NightMessenger#23]
Before:
![image](https://user-images.githubusercontent.com/17950836/59861147-e5445d00-9345-11e9-941f-66c172a47ebd.png)

After:
![image](https://user-images.githubusercontent.com/17950836/59861340-3eac8c00-9346-11e9-83ff-2bb5abcf357a.png)

Fix:
```
._aou,
._4owc ._53ij
{
  background: #808080 !important;
}
```

**Comment by aflashyrhetoric** [comment]
Hello @blakebuthod ! Thank you for the fix, I'll test it and release it soon. !

**Comment by aflashyrhetoric** [comment]
Works - thank you very much! I'll merge and release soon. Closing, and added you to CONTRIBUTORS.md
